-- DEV ONLY: 24 pending-review candidates across 18 previously empty counties.
-- Generated by tools/places/generate_county_gap_seed.py.
-- Sources, coordinate methods, Maps review links and review notes:
-- data/places/dev_county_gap_places.json (no Google reviews/ratings/photos copied).
-- No schema changes. Uses the existing places fields and category mappings.
--
-- Default is a no-op, including when this migration reaches production.
-- To seed DEV, execute in one SQL session/transaction:
--   BEGIN;
--   SET LOCAL app.seed_dev_places = 'on';
--   <contents of this migration>
--   COMMIT;
-- If migration history already recorded the no-op, explicitly rerun this file
-- with the opt-in in the DEV SQL editor. No database reset is necessary.
-- Never enable the setting in production. Approval/promotion is future work.
--
-- Source IDs make reruns idempotent. Existing records are preserved, including
-- edits made during review. County mismatches and cross-source name duplicates
-- abort the entire seed instead of silently dropping or misassigning places.

do $dev_places$
declare
  candidate record;
  matched_count integer;
begin
  if current_setting('app.seed_dev_places', true) is distinct from 'on' then
    raise notice 'Skipping pending-review dev places; app.seed_dev_places is not on';
    return;
  end if;

  for candidate in
    select * from (values
    (1, 'Haller Park', 'park', 'A restored quarry landscape with wildlife and walking trails.', 'Haller Park is a nature attraction in Bamburi, Mombasa. Its restored quarry landscape provides a setting for viewing wildlife and exploring planted woodland.', -4.0158805, 39.7215955, 'OpenStreetMap', 'https://www.openstreetmap.org/node/650087603', 'ODbL 1.0', 'osm:node:650087603', '2026-09-09'),
    (2, 'Kaya Kinondo Sacred Forest', 'heritage', 'A Digo sacred forest and community heritage destination.', 'Kaya Kinondo is a sacred forest associated with the Digo community on the south coast. Visits should be arranged with the community guides and follow their rules for entering the forest.', -4.3949304, 39.5458972, 'OpenStreetMap', 'https://www.openstreetmap.org/way/1184970190', 'ODbL 1.0', 'osm:way:1184970190', '2026-09-09'),
    (14, 'Karue Hill', 'culture', 'A rocky hill landmark in the Embu highlands.', 'Karue Hill is a prominent landscape landmark in Embu County. Its rock formations and surrounding highland scenery make it a candidate for a locally guided visit. The mapped point marks the hill rather than an established trailhead.', -0.46103, 37.53945, 'GeoNames', 'https://www.geonames.org/193604/', 'CC BY 4.0', 'geonames:193604', '2026-09-09'),
    (14, 'Mwea National Reserve', 'park', 'A wildlife reserve beside the lower Tana reservoir landscape.', 'Mwea National Reserve is a protected landscape in Embu County. The reserve offers a setting for wildlife observation and birdwatching in the lower Tana area.', -0.8191038, 37.6160752, 'OpenStreetMap', 'https://www.openstreetmap.org/way/321638202', 'ODbL 1.0', 'osm:way:321638202', '2026-09-09'),
    (16, 'Machakos People''s Park', 'park', 'A public recreation park on the outskirts of Machakos.', 'Machakos People''s Park is an outdoor recreation destination near Machakos town. This record represents the mapped park grounds; event arrangements and access should be checked before a visit.', -1.539544, 37.2337629, 'OpenStreetMap', 'https://www.openstreetmap.org/way/292443263', 'ODbL 1.0', 'osm:way:292443263', '2026-09-09'),
    (16, 'Ol Donyo Sabuk', 'culture', 'A mountain landmark overlooking the surrounding plains.', 'Ol Donyo Sabuk is a mountain in Machakos County. This record marks the mapped summit landmark, not the national park entrance. Visitor routes and access need confirmation before production use.', -1.1414008, 37.2572725, 'OpenStreetMap', 'https://www.openstreetmap.org/node/467077879', 'ODbL 1.0', 'osm:node:467077879', '2026-09-09'),
    (18, 'Lake Ol Bolossat', 'shore', 'A highland lake and wetland landscape in Nyandarua.', 'Lake Ol Bolossat is a freshwater lake in Nyandarua County. This record identifies the lake landscape; the representative waterbody coordinate must be replaced with a reviewed shore access point before offering production directions.', -0.15505, 36.44468, 'GeoNames', 'https://www.geonames.org/196396/', 'CC BY 4.0', 'geonames:196396', '2026-09-09'),
    (18, 'Mount Kipipiri', 'culture', 'A mountain landmark beside the Aberdare highlands.', 'Mount Kipipiri is a highland mountain in Nyandarua County. The seed uses the mapped mountain point as a research marker. Confirm an appropriate hiking route and visitor entry point during review.', -0.4274162, 36.5382311, 'OpenStreetMap', 'https://www.openstreetmap.org/node/318234824', 'ODbL 1.0', 'osm:node:318234824', '2026-09-09'),
    (20, 'Castle Forest Lodge', 'stay', 'A forest lodge on the southern slopes of Mount Kenya.', 'Castle Forest Lodge offers accommodation in the forest on the southern side of Mount Kenya. The surrounding setting includes forest and rivers; available activities and access should be confirmed with the lodge.', -0.38103, 37.3109112, 'OpenStreetMap', 'https://www.openstreetmap.org/node/3268549607', 'ODbL 1.0', 'osm:node:3268549607', '2026-09-09'),
    (21, 'Rapids Camp', 'stay', 'A riverside camp near Sagana with outdoor activities.', 'Rapids Camp is a camping and accommodation destination in Murang''a County near Sagana. Its operator offers river-based and group activities; arrange the intended visit directly with the camp.', -0.6963326, 37.2424811, 'OpenStreetMap', 'https://www.openstreetmap.org/node/2485704405', 'ODbL 1.0', 'osm:node:2485704405', '2026-09-09'),
    (22, 'Paradise Lost', 'culture', 'A Kiambu visitor destination with caves and picnic areas.', 'Paradise Lost is a visitor attraction in Kiambu County associated with caves and outdoor recreation. The mapped attraction point is retained for dev review; check activity access and the correct visitor entrance before production.', -1.1878891, 36.825963, 'OpenStreetMap', 'https://www.openstreetmap.org/node/10080463218', 'ODbL 1.0', 'osm:node:10080463218', '2026-09-09'),
    (25, 'Samburu National Reserve', 'park', 'A protected wildlife landscape north of the Ewaso Nyiro River.', 'Samburu National Reserve is a wildlife destination in Samburu County. This record uses the mapped reserve point; the appropriate gate should be selected during review for visitor directions.', 0.6155747, 37.5371646, 'OpenStreetMap', 'https://www.openstreetmap.org/relation/20574204', 'ODbL 1.0', 'osm:relation:20574204', '2026-09-09'),
    (27, 'Poa Place Resort', 'stay', 'An Eldoret resort with accommodation and visitor attractions.', 'Poa Place Resort is an accommodation and leisure destination in Eldoret. Its visitor facilities include a nature and culture centre; confirm current activities and entrance arrangements with the operator.', 0.5061287, 35.3012201, 'OpenStreetMap', 'https://www.openstreetmap.org/way/388612179', 'ODbL 1.0', 'osm:way:388612179', '2026-09-09'),
    (29, 'Nandi Rock', 'culture', 'A rocky viewpoint on the Nandi escarpment.', 'Nandi Rock is a landscape landmark on the Nandi escarpment, also recorded as Nyando Rock. The seed point marks the rock; review the hiking approach and access arrangements before production.', -0.01667, 34.86667, 'GeoNames', 'https://www.geonames.org/184469/', 'CC BY 4.0', 'geonames:184469', '2026-09-09'),
    (35, 'Kericho Market', 'market', 'A local market in Kericho town.', 'Kericho Market is a mapped marketplace in the centre of Kericho. It is included as a community and everyday-trade destination for dev review; trading days and visitor access have not been verified.', -0.3645499833333334, 35.28795855, 'OpenStreetMap', 'https://www.openstreetmap.org/way/1098212462', 'ODbL 1.0', 'osm:way:1098212462', '2026-09-09'),
    (35, 'Uhuru Gardens, Kericho', 'park', 'A mapped public garden in central Kericho.', 'Uhuru Gardens is a mapped park in Kericho town. It provides an urban green-space candidate for the dev catalogue. Confirm the public entrance and current facilities during editorial review.', -0.3682701888888889, 35.283641277777775, 'OpenStreetMap', 'https://www.openstreetmap.org/way/173069082', 'ODbL 1.0', 'osm:way:173069082', '2026-09-09'),
    (36, 'Brevan Hotel', 'stay', 'An accommodation stop in Bomet town.', 'Brevan Hotel is an accommodation destination in Bomet listed by the county tourism department. This dev entry does not imply a quality rating or verified room availability.', -0.7845781, 35.344254, 'OpenStreetMap', 'https://www.openstreetmap.org/node/3143180715', 'ODbL 1.0', 'osm:node:3143180715', '2026-09-09'),
    (37, 'Crying Stone of Ilesi', 'culture', 'A rock landmark associated with local cultural traditions.', 'The Crying Stone of Ilesi, also known as Ikhonga Murwi, is a distinctive rock landmark near Kakamega. It is associated with local cultural traditions; confirm access and guiding arrangements during review.', 0.2406774, 34.7555889, 'OpenStreetMap', 'https://www.openstreetmap.org/node/4404819572', 'ODbL 1.0', 'osm:node:4404819572', '2026-09-09'),
    (37, 'Nabongo Cultural Centre', 'culture', 'A cultural centre associated with the Wanga kingdom.', 'Nabongo Cultural Centre is a heritage destination in the Matungu area of Kakamega County. The centre introduces the history and traditions of the Wanga kingdom.', 0.391607, 34.4772192, 'OpenStreetMap', 'https://www.openstreetmap.org/way/368890622', 'ODbL 1.0', 'osm:way:368890622', '2026-09-09'),
    (38, 'Chango Market', 'market', 'A community marketplace in Vihiga County.', 'Chango is a mapped marketplace in Vihiga County. It is a local-trade candidate for the dev catalogue; confirm its preferred public name, trading days and access during review.', 0.0704686, 34.7187805, 'OpenStreetMap', 'https://www.openstreetmap.org/node/7232815589', 'ODbL 1.0', 'osm:node:7232815589', '2026-09-09'),
    (38, 'Maragoli Hills', 'culture', 'A hill landscape with local cultural significance.', 'The Maragoli Hills are a landscape and heritage destination in Vihiga County. The seed uses the gazetteer hill point; a visitor route, entrance and any local guiding arrangements still need review.', 0.00075, 34.66928, 'GeoNames', 'https://www.geonames.org/187740/', 'CC BY 4.0', 'geonames:187740', '2026-09-09'),
    (40, 'Kakapel National Monument', 'heritage', 'A rock-art and cultural heritage site in Teso North.', 'Kakapel is a rock-art heritage destination in Busia County, near Chelelemuk Hill. The site is recognised by the county as a national monument and cultural attraction.', 0.6679963, 34.359024, 'OpenStreetMap', 'https://www.openstreetmap.org/node/13516456501', 'ODbL 1.0', 'osm:node:13516456501', '2026-09-09'),
    (45, 'Daraja Mbili Market', 'market', 'A mapped marketplace in Kisii town.', 'Daraja Mbili Market is a local-trade destination in Kisii town. The seed retains its mapped market location without assuming particular trading days or visitor facilities.', -0.6665466, 34.7642373, 'OpenStreetMap', 'https://www.openstreetmap.org/node/6140754298', 'ODbL 1.0', 'osm:node:6140754298', '2026-09-09'),
    (46, 'Manga Ridge', 'culture', 'A highland ridge overlooking the Kisii-Nyamira landscape.', 'Manga Ridge is a scenic and culturally significant landscape in Nyamira County. This representative ridge point needs review for the appropriate public access route before use in production directions.', -0.63029, 34.81869, 'GeoNames', 'https://www.geonames.org/187875/', 'CC BY 4.0', 'geonames:187875', '2026-09-09')
    ) as raw_places (
      county_id, name, type, summary, description, lat, lng,
      source, source_url, licence, external_id, last_verified_at
    )
  loop
    select count(*) into matched_count
    from public.counties c
    where c.id = candidate.county_id
      and extensions.ST_Covers(
        c.geometry,
        extensions.ST_SetSRID(extensions.ST_MakePoint(candidate.lng, candidate.lat), 4326)
      );
    if matched_count <> 1 then
      raise exception 'Dev seed county/geometry mismatch: % (county %)',
        candidate.name, candidate.county_id;
    end if;

    if exists (
      select 1 from public.places p
      where p.county_id = candidate.county_id
        and lower(trim(p.name)) = lower(trim(candidate.name))
        and (p.source, p.external_id) is distinct from
            (candidate.source, candidate.external_id)
    ) then
      raise exception 'Review cross-source duplicate before seeding: %', candidate.name;
    end if;

    if exists (
      select 1 from public.places p
      where p.source = candidate.source and p.external_id = candidate.external_id
        and p.county_id <> candidate.county_id
    ) then
      raise exception 'Existing place has a different county: %', candidate.name;
    end if;

    insert into public.places (
      county_id, name, type, summary, description, location,
      source, source_url, licence, external_id, last_verified_at
    ) values (
      candidate.county_id, candidate.name, candidate.type,
      candidate.summary, candidate.description,
      extensions.ST_SetSRID(extensions.ST_MakePoint(candidate.lng, candidate.lat), 4326),
      candidate.source, candidate.source_url, candidate.licence,
      candidate.external_id, candidate.last_verified_at::date
    )
    on conflict (source, external_id) where external_id is not null do nothing;
  end loop;
end;
$dev_places$;
