-- County highlight image seed from Wikimedia Commons file search.
-- Generated from data/counties/highlight_images_raw.json with manual review
-- of obvious false positives. Skipped for now: bungoma, embu, garissa, isiolo, kakamega, kwale, mandera, tharaka-nithi, vihiga.
-- Remote URLs and attribution metadata are stored; no image binaries are
-- downloaded or redistributed by this migration.

with raw_county_highlight_images (
  county_id,
  county_slug,
  highlight_image_url,
  highlight_image_source,
  highlight_image_source_url,
  highlight_image_licence,
  highlight_image_licence_url,
  highlight_image_attribution,
  highlight_image_last_verified_at
) as (
  values
    (1, 'mombasa', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Fun_at_Shelly_Beach_Mombasa.jpg/1280px-Fun_at_Shelly_Beach_Mombasa.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Fun_at_Shelly_Beach_Mombasa.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'MariamSaria', '2026-09-03'),
    (3, 'kilifi', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5c/Kilifi%2C_Kenya_%2846493461342%29.jpg/1280px-Kilifi%2C_Kenya_%2846493461342%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Kilifi,_Kenya_(46493461342).jpg', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0', 'Nina R from Africa', '2026-09-03'),
    (4, 'tana-river', 'https://upload.wikimedia.org/wikipedia/commons/2/24/Bridge_over_the_Tana_river_%28Kenya%29.JPEG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Bridge_over_the_Tana_river_(Kenya).JPEG', 'Public domain', null, 'SGT R.A. Ward, U.S. Marine Corps', '2026-09-03'),
    (5, 'lamu', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/34/Traditional_dhow_sailboat_in_Lamu%2C_Kenya.jpg/1280px-Traditional_dhow_sailboat_in_Lamu%2C_Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Traditional_dhow_sailboat_in_Lamu,_Kenya.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Elena.laps', '2026-09-03'),
    (6, 'taita-taveta', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3e/Buchuma_Gate_-_Tsavo_East_National_Park_Kenya_-_panoramio.jpg/1280px-Buchuma_Gate_-_Tsavo_East_National_Park_Kenya_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Buchuma_Gate_-_Tsavo_East_National_Park_Kenya_-_panoramio.jpg', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0', 'D Heaysman', '2026-09-03'),
    (8, 'wajir', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/43/Giraffe_in_wajir%2C_Kenya.jpg/1280px-Giraffe_in_wajir%2C_Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Giraffe_in_wajir,_Kenya.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Zachyare', '2026-09-03'),
    (10, 'marsabit', 'https://upload.wikimedia.org/wikipedia/commons/2/2f/KE_Marsabit_0204_001_%2817064031409%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:KE_Marsabit_0204_001_(17064031409).jpg', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0', 'Diego Tirira from Quito, Ecuador', '2026-09-03'),
    (12, 'meru', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/d/dd/Meru_zebra_-_panoramio.jpg/1280px-Meru_zebra_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Meru_zebra_-_panoramio.jpg', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0', 'Jan Hazevoet', '2026-09-03'),
    (15, 'kitui', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ae/Kitui_County%2C_Kenya_-_panoramio.jpg/1280px-Kitui_County%2C_Kenya_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Kitui_County,_Kenya_-_panoramio.jpg', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0', 'D Heaysman', '2026-09-03'),
    (16, 'machakos', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/45/Sand_Harvesting-Tala%2C_Kenya_2.jpg/1280px-Sand_Harvesting-Tala%2C_Kenya_2.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Sand_Harvesting-Tala,_Kenya_2.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Quitworkbaninja', '2026-09-03'),
    (17, 'makueni', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/2/2b/Chyulu_Hills%2C_Kenya_%28Unsplash%29.jpg/1280px-Chyulu_Hills%2C_Kenya_%28Unsplash%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Chyulu_Hills,_Kenya_(Unsplash).jpg', 'CC0', 'http://creativecommons.org/publicdomain/zero/1.0/deed.en', 'Sho Hatakeyama shohatakeyama', '2026-09-03'),
    (18, 'nyandarua', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5f/Lake_Olbolosat.jpg/1280px-Lake_Olbolosat.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Lake_Olbolosat.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Kiyo Nganga', '2026-09-03'),
    (19, 'nyeri', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/7/77/Two_men_in_Kenya%27s_Nyeri_County_ride_horses_as_a_means_of_transport_to_traverse_the_mountainous_terrain.png/1280px-Two_men_in_Kenya%27s_Nyeri_County_ride_horses_as_a_means_of_transport_to_traverse_the_mountainous_terrain.png?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Two_men_in_Kenya%27s_Nyeri_County_ride_horses_as_a_means_of_transport_to_traverse_the_mountainous_terrain.png', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Joseph Ritho', '2026-09-03'),
    (20, 'kirinyaga', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/6/67/View_of_Mt._Kenya_from_Nanyuki_Town_2020.jpg/1280px-View_of_Mt._Kenya_from_Nanyuki_Town_2020.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:View_of_Mt._Kenya_from_Nanyuki_Town_2020.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Martin Kithinji Mwirigi', '2026-09-03'),
    (21, 'murang-a', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/a/ae/Kenol%2C_Murang%27a_Kenya_MArket.jpg/1280px-Kenol%2C_Murang%27a_Kenya_MArket.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Kenol,_Murang%27a_Kenya_MArket.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Robertwhisps', '2026-09-03'),
    (22, 'kiambu', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/4a/Tea_plantation_landscape_in_Cianda%2C_Kiambu_County_01.jpg/1280px-Tea_plantation_landscape_in_Cianda%2C_Kiambu_County_01.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Tea_plantation_landscape_in_Cianda,_Kiambu_County_01.jpg', 'CC BY 4.0', 'https://creativecommons.org/licenses/by/4.0', 'Lebu Ayiga', '2026-09-03'),
    (23, 'turkana', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9f/Lake_Turkana_in_Kenya_02.jpg/1280px-Lake_Turkana_in_Kenya_02.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Lake_Turkana_in_Kenya_02.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'CaptChandra', '2026-09-03'),
    (24, 'west-pokot', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/fa/Landscapes_of_Kenya_12.jpg/1280px-Landscapes_of_Kenya_12.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Landscapes_of_Kenya_12.jpg', 'CC BY 2.0', 'https://creativecommons.org/licenses/by/2.0', 'flightlog', '2026-09-03'),
    (25, 'samburu', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/52/Maralal_International_Camel_Derby_Yare_Samburu_Cultural_festival_By_Antony_Trivet_Travel_Documentary_Photography_In_Kenya-402.jpg/1280px-Maralal_International_Camel_Derby_Yare_Samburu_Cultural_festival_By_Antony_Trivet_Travel_Documentary_Photography_In_Kenya-402.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Maralal_International_Camel_Derby_Yare_Samburu_Cultural_festival_By_Antony_Trivet_Travel_Documentary_Photography_In_Kenya-402.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Antony Trivet', '2026-09-03'),
    (26, 'trans-nzoia', 'https://upload.wikimedia.org/wikipedia/commons/d/de/Cherubei_Villege%2C_Mt._Elgon%2C_Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Cherubei_Villege,_Mt._Elgon,_Kenya.jpg', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0', 'Nlorusso', '2026-09-03'),
    (27, 'uasin-gishu', 'https://upload.wikimedia.org/wikipedia/commons/a/ae/Turbo-_Uasin_Gishu_county_-Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Turbo-_Uasin_Gishu_county_-Kenya.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Faraj Jamil', '2026-09-03'),
    (28, 'elgeyo-marakwet', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/06/Arror_view%2C_elgeyo-marakwet%2C_Kenya.jpg/1280px-Arror_view%2C_elgeyo-marakwet%2C_Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Arror_view,_elgeyo-marakwet,_Kenya.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Dun Sang', '2026-09-03'),
    (29, 'nandi', 'https://upload.wikimedia.org/wikipedia/commons/e/e0/Mogobich_Valley%2C_Nandi_Hills.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Mogobich_Valley,_Nandi_Hills.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Eren Gatiat', '2026-09-03'),
    (30, 'baringo', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f0/Kenyan_crocodile_%28Crocodylus_niloticus_pauciscutatus%29.jpg/1280px-Kenyan_crocodile_%28Crocodylus_niloticus_pauciscutatus%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Kenyan_crocodile_(Crocodylus_niloticus_pauciscutatus).jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Charles J. Sharp', '2026-09-03'),
    (31, 'laikipia', 'https://upload.wikimedia.org/wikipedia/commons/8/8d/Karisia_Walking_Safaris_Camels_in_Laikipia%2C_Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Karisia_Walking_Safaris_Camels_in_Laikipia,_Kenya.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Karisiasafaris', '2026-09-03'),
    (32, 'nakuru', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cc/Zebra_Lake_Nakuru-close_view.jpg/1280px-Zebra_Lake_Nakuru-close_view.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Zebra_Lake_Nakuru-close_view.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Lyfec', '2026-09-03'),
    (33, 'narok', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/b/b7/Kenya%2C_2013._The_road_Keekorok-Narok_-_panoramio.jpg/1280px-Kenya%2C_2013._The_road_Keekorok-Narok_-_panoramio.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Kenya,_2013._The_road_Keekorok-Narok_-_panoramio.jpg', 'CC BY 3.0', 'https://creativecommons.org/licenses/by/3.0', 'Roma Neus', '2026-09-03'),
    (34, 'kajiado', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/0/03/Sunset_on_Kamwar%C3%AE_in_Ongata_Rongai%2C_Kajiado_County%2C_Kenya.jpg/1280px-Sunset_on_Kamwar%C3%AE_in_Ongata_Rongai%2C_Kajiado_County%2C_Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Sunset_on_Kamwar%C3%AE_in_Ongata_Rongai,_Kajiado_County,_Kenya.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'David N. Munene', '2026-09-03'),
    (35, 'kericho', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/5/5e/KER_-_Agricultural_landscape_near_Kericho%2C_Kenya%2C_2012.jpg/1280px-KER_-_Agricultural_landscape_near_Kericho%2C_Kenya%2C_2012.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:KER_-_Agricultural_landscape_near_Kericho,_Kenya,_2012.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Josep M. Gracia', '2026-09-03'),
    (36, 'bomet', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3f/Dairy_Farming_in_Bomet%2C_Kenya.jpg/1280px-Dairy_Farming_in_Bomet%2C_Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Dairy_Farming_in_Bomet,_Kenya.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Korirhilla', '2026-09-03'),
    (40, 'busia', 'https://upload.wikimedia.org/wikipedia/commons/2/23/Platter_of_fried_pork_in_Busia%2C_Kenya_-_03.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Platter_of_fried_pork_in_Busia,_Kenya_-_03.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Lebu Ayiga', '2026-09-03'),
    (41, 'siaya', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/f/f7/Pines_in_Siaya%28Kenya%29.jpg/1280px-Pines_in_Siaya%28Kenya%29.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Pines_in_Siaya(Kenya).jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Adrie Manolo', '2026-09-03'),
    (42, 'kisumu', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/9/9c/KISU_-_Fisherman_returning_at_sunset_on_Lake_Victoria%2C_Kisumu%2C_Kenya%2C_2012.jpg/1280px-KISU_-_Fisherman_returning_at_sunset_on_Lake_Victoria%2C_Kisumu%2C_Kenya%2C_2012.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:KISU_-_Fisherman_returning_at_sunset_on_Lake_Victoria,_Kisumu,_Kenya,_2012.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Josep M. Gracia', '2026-09-03'),
    (43, 'homa-bay', 'https://upload.wikimedia.org/wikipedia/commons/e/e9/Homa_Hills%2C_Homabay_County%2C_Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail_unscaled', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Homa_Hills,_Homabay_County,_Kenya.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Taming marduk', '2026-09-03'),
    (44, 'migori', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/c/cf/Thimlich_Ohinga_Cultural_Landscape-_Kenya.JPG/1280px-Thimlich_Ohinga_Cultural_Landscape-_Kenya.JPG?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Thimlich_Ohinga_Cultural_Landscape-_Kenya.JPG', 'CC BY-SA 3.0', 'https://creativecommons.org/licenses/by-sa/3.0', 'Wycondi', '2026-09-03'),
    (45, 'kisii', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/3b/Business_at_Marikiti_Market_in_Kisii_County_%2CKenya_%2CEast_Africa.jpg/1280px-Business_at_Marikiti_Market_in_Kisii_County_%2CKenya_%2CEast_Africa.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Business_at_Marikiti_Market_in_Kisii_County_,Kenya_,East_Africa.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'Janetnyanya', '2026-09-03'),
    (46, 'nyamira', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/4/44/Keera_waterfall_in_Nyamira%2C_Kenya.jpg/1280px-Keera_waterfall_in_Nyamira%2C_Kenya.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Keera_waterfall_in_Nyamira,_Kenya.jpg', 'CC BY-SA 4.0', 'https://creativecommons.org/licenses/by-sa/4.0', 'ColloFlix', '2026-09-03'),
    (47, 'nairobi', 'https://thumb.wikimedia.org/wikipedia/commons/thumb/3/33/Gyps_rueppellii_-Nairobi_National_Park%2C_Kenya-8-4c.jpg/1280px-Gyps_rueppellii_-Nairobi_National_Park%2C_Kenya-8-4c.jpg?utm_source=commons.wikimedia.org&utm_campaign=imageinfo&utm_content=thumbnail', 'Wikimedia Commons', 'https://commons.wikimedia.org/wiki/File:Gyps_rueppellii_-Nairobi_National_Park,_Kenya-8-4c.jpg', 'CC BY-SA 2.0', 'https://creativecommons.org/licenses/by-sa/2.0', 'Gyps_rueppellii_-Nairobi_National_Park,_Kenya-8.jpg : Jorge Láscar from Bogotá, Colombia derivative work: Snowmanradio ( talk )', '2026-09-03')
)
update public.counties
set
  highlight_image_url = raw_county_highlight_images.highlight_image_url,
  highlight_image_source = raw_county_highlight_images.highlight_image_source,
  highlight_image_source_url = raw_county_highlight_images.highlight_image_source_url,
  highlight_image_licence = raw_county_highlight_images.highlight_image_licence,
  highlight_image_licence_url = raw_county_highlight_images.highlight_image_licence_url,
  highlight_image_attribution = raw_county_highlight_images.highlight_image_attribution,
  highlight_image_last_verified_at =
    raw_county_highlight_images.highlight_image_last_verified_at::date
from raw_county_highlight_images
where counties.id = raw_county_highlight_images.county_id
  and counties.slug = raw_county_highlight_images.county_slug;
